---
- include: system.yml
  tags:
    - system

- include: aws.yml
  tags:
    - third-party
    - aws

- include: fedy.yml
  tags:
    - third-party
    - fedy

- include: chrome.yml
  tags:
    - third-party
    - chrome

- include: vscode.yml
  tags:
    - third-party
    - vscode

- include: insync.yml
  tags:
    - third-party
    - insync

- include: nordvpn.yml
  tags:
    - third-party
    - nordvpn

- include: docker.yml
  tags:
    - third-party
    - docker

- include: kubernetes.yml
  tags:
    - third-party
    - kubernetes

- include: php.yml
  tags:
    - php

- include: java.yml
  tags:
    - java

- include: kafka.yml
  tags:
    - third-party
    - kafka

- include: terraform.yml
  tags:
    - third-party
    - terraform

- name: Install Flatpak packages
  flatpak:
    name: '{{ item }}'
    state: present
  with_items:
    - com.slack.Slack
    - com.spotify.Client
    - us.zoom.Zoom
  tags:
    - third-party
    - flatpak

- name: Install Snap packages
  snap:
    classic: true
    name:
      - nordpass
      - postman
